logging:
  level:
    com:
      inso_world:
        binocular: trace
#    root: warn
server:
  port: 8080
spring:
  profiles:
    active: nosql, arangodb
  application:
    name: binocular
  graphql:
    graphiql:
      enabled: true
