logging:
  level:
    com:
      inso_world:
        binocular: trace
#    root: warn
server:
  port: 48763
spring:
  profiles:
    active: nosql, arangodb
  application:
    name: binocular
  graphql:
    path: /graphQl
    graphiql:
      enabled: true
