logging:
  level:
    com:
      inso_world:
        binocular: trace
#    root: warn
server:
  port: 48763
spring:
  profiles:
    active: nosql, arangodb
    # active: sql, postgresql
  application:
    name: binocular
  graphql:
    http:
      path: '/graphQl'
    graphiql:
      enabled: true
