spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/binocular
    username: ${DATABASE_USER:binocular}
    password: ${DATABASE_PW:binocular}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 256
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        order_updates: true
#        order_inserts: true
#        batch_versioned_data: true
#        generate_statistics: true
#        show_sql: true
logging:
#  level:
#    org:
#      hibernate:
#        engine:
#          internal:
#            StatisticalLoggingSessionEventListener: info
