binocular:
  index:
    path: "/Users/rise/Repositories/test_repositories/Binocular"
spring:
  profiles:
    active: arangodb
  main:
    web-application-type: none
#    banner-mode: off
  application:
    name: binocular-cli
  shell:
    script:
      enabled: true
    interactive:
      enabled: true
## disable console logging
logging:
  level:
    com:
      inso_world:
        binocular: trace
    root: warn
