# Assuming a Custom Type named URL using a String as the builtin.
[bindings.kotlin]
package_name="com.inso_world.binocular.cli.uniffi"
cdylib_name="mylib"
#omit_checksums=true

[bindings.kotlin.custom_types.Point]
type_name="Point"
lift = "Point({})"
lower = "{}.toString()"