name: backend.yml

on:
  push:
    branches:
      - main
      - develop
      - 'feature/backend-new-gha'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        #        os: [ubuntu-latest, windows-latest, macos-latest]
        java_version: [ '21', '23' ]
        distribution: [ 'temurin' ]
        os: [ ubuntu-latest ]
        architecture: [ 'x64' ]
        include:
          - os: ubuntu-24.04-arm
            architecture: 'aarch64'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.distribution }}/${{ matrix.java_version }} for ${{ matrix.architecture }}
        uses: actions/setup-java@v4
        with:
          cache: 'maven'
          #          cache-dependency-path: 'sub-project/pom.xml' # optional
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.distribution }}
          architecture: ${{ matrix.architecture }}
      - name: Verify Parent with Maven
        run: mvn -B validate --file binocular-backend-new/pom.xml
      - name: Compile with Maven
        run: mvn -B compile --file binocular-backend-new/pom.xml
