name: Backend CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/backend-new-gha'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
        java_version: [ '21', '23' ]
        distribution: [ 'temurin' ]
        include:
          - os: ubuntu-latest
            architecture: 'x64'
          - os: ubuntu-24.04-arm
            architecture: 'aarch64'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.distribution }}/${{ matrix.java_version }} for ${{ matrix.architecture }}
        uses: actions/setup-java@v4
        with:
          cache: 'maven'
          cache-dependency-path: '**/pom.xml' # optional
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.distribution }}
          architecture: ${{ matrix.architecture }}

      - name: Verify Parent with Maven
        run: mvn $MAVEN_CLI_OPTS validate --file binocular-backend-new/pom.xml

      - name: Compile with Maven
        run: mvn $MAVEN_CLI_OPTS compile --file binocular-backend-new/pom.xml

  test:
    name: Test
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
        java_version: [ '21', '23' ]
        distribution: [ 'temurin' ]
        module: [ 'web', 'core' ]
        include:
          - os: ubuntu-latest
            architecture: 'x64'
          - os: ubuntu-24.04-arm
            architecture: 'aarch64'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.distribution }}/${{ matrix.java_version }} for ${{ matrix.architecture }}
        uses: actions/setup-java@v4
        with:
          cache: 'maven'
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.distribution }}
          architecture: ${{ matrix.architecture }}

      - name: Run tests for module ${{ matrix.module }}
        run: mvn $MAVEN_CLI_OPTS verify --file binocular-backend-new/${{ matrix.module }}/pom.xml
